In [56]:
import numpy as np


# Numpy Exercises

### 1. How many negative numbers are there?
Use the following code for the questions below:

 a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int64')

In [7]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [18]:
mask = a < 0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [19]:
a[mask]

array([-2, -1, -6, -7])

### 2. How many positive numbers are there?

In [20]:
a[~mask]

array([ 4, 10, 12, 23,  0,  0,  0,  3])

### 3. How many even positive numbers are there?


In [33]:
mask = (a % 2 == 0) & (a > 0)
a[mask]

array([ 4, 10, 12])

### 4. If you were to add 3 to each data point, how many positive numbers would there be?


In [41]:
b = a + 3
b
mask = b > 0
b[mask]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

### 5. If you squared each number, what would the new mean and standard deviation be?


In [44]:
c = a ** 2
c
np.mean(c)

74.0

In [45]:
np.std(c)

144.0243035046516

### 6. A common statistical operation on a dataset is centering. 
   This means to adjust the data such that the mean of the data is 0. 
   This is done by subtracting the mean from each data point. 
   Center the data set. See this link for more on centering.


In [49]:
mean_a = np.mean(a)
mean_a

3.0

In [50]:
centered = a - mean_a
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

### 7. Calculate the z-score for each data point. Recall that the z-score is given by:

    Z = (x - μ) / σ

In [53]:
std_a = np.std(a)
std_a

8.06225774829855

In [55]:
zscore_a = (a - mean_a)/std_a
zscore_a

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Use python's built in functionality/operators to determine the following:

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [67]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [69]:
sum_of_a = sum(a)
sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [70]:
min_of_a = min(a)
min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [71]:
max_of_a = max(a)
max_of_a

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [76]:
mean_of_a = sum_of_a/len(a)
mean_of_a

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [79]:
product_of_a = np.prod(a)
product_of_a


3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [82]:
array_1 = np.array(a)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
squares_of_a = array_1 ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [91]:
mask = (array_1 % 2 != 0)
odds_in_a = array_1 [mask]
odds_in_a

array([1, 3, 5, 7, 9])

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [92]:
mask = (array_1 % 2 == 0)
evens_in_a = array_1 [mask]
evens_in_a

array([ 2,  4,  6,  8, 10])

## Setup 2 

Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
  
  What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [93]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 

Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [96]:
b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [98]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

### Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

In [106]:
min(b[0])

3

In [102]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
min_of_b


3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [103]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

### Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [104]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [111]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [112]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

### Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [113]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

### Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [114]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

### Exercise 9 - print out the shape of the array b.


In [115]:
b.shape

(2, 3)

### Exercise 10 - transpose the array b.


In [118]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [117]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [120]:
np.reshape(b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [121]:
np.reshape(b,(6,1))

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

 HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.


In [123]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [125]:
c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Exercise 1 - Find the min, max, sum, and product of c.


In [128]:
c1 = np.reshape(c,(1,9))
c1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [130]:
min_of_c = c1.min()
min_of_c

1

In [131]:
max_of_c = c1.max()
max_of_c

9

In [133]:
sum_of_c = c1.sum()
sum_of_c

45

In [134]:
product_of_c = c1.prod()
product_of_c

362880

### Exercise 2 - Determine the standard deviation of c.


In [138]:
std_of_c = c1.std()
std_of_c

2.581988897471611

### Exercise 3 - Determine the variance of c.


In [140]:
var_of_c = c1.var()
var_of_c

6.666666666666667

### Exercise 4 - Print out the shape of the array c


In [141]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.


In [143]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
transpose_c = np.transpose(c)
transpose_c

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c. 


In [147]:
dot_c = np.dot(c,c)
dot_c

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [152]:
c_times_tc = c * transpose_c
c_times_tc
reshape_c = np.reshape(c_times_tc,(1,9))
reshape_c
np.sum(reshape_c)

261

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [153]:
np.prod(reshape_c)

131681894400

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]


In [177]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]



### Exercise 1 - Find the sine of all the numbers in d


In [178]:
d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [179]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 3 - Find the tangent of all the numbers in d


In [180]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d


In [181]:
reshape_d = np.reshape(d,(1,18))
mask = (reshape_d < 0)
reshape_d[mask]

array([-90, -30, -45, -45])

### Exercise 5 - Find all the positive numbers in d


In [182]:
mask = (reshape_d > 0)
reshape_d[mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

### Exercise 6 - Return an array of only the unique numbers in d.


In [183]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.


In [192]:
unique_d = np.unique(d)
count_d = len(unique_d)
print(count_d)

11


### Exercise 8 - Print out the shape of d.


In [186]:
unique_d = np.unique(d)
unique_d.shape

(11,)

### Exercise 9 - Transpose and then print out the shape of d.


In [194]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [193]:
transpose_d = np.transpose(d)
transpose_d

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

### Exercise 10 - Reshape d into an array of 9 x 2


In [196]:
reshape_d = np.reshape(d,(9,2))
reshape_d


array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])